version: "3"

services:
  db_node:
    image: mariadb:10.9.1-rc
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_PASSWORD: An0thrS3crt
      MYSQL_USER: mariadb_user
    container_name: some_mariadb

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db_node

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 5000:80
    environment:
      PMA_HOST: db_node
      PMA_USER: mariadb_user
      PMA_PASSWORD: An0thrS3crt
    depends_on:
      - db_node
volumes:
  db_data:
#     external: true
