services:
  mc_norm:
    container_name: mc_norm
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      MOTD: "server MOTD"
      EULA: "TRUE"
      MEMORY: "4G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "adminpass"
      RCON_PORT: 28016
      PVP: "false"
      ENABLE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      WHITELIST: "user1,user2"
    restart: always
    volumes:
      - ./mc_norm:/data
