services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8314:80
      - 4314:443
    environment:
      TZ: America/Denver
      DNSMASQ_LISTENING: all
    volumes:
      - ./pihole_data_dir:/etc/pihole
      - ./dnsmasq_data_dir:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    networks:
      - pihole_net
    entrypoint: ["/bin/sh", "-c", "echo 'nameserver 127.0.0.1' >> /etc/resolv.conf && exec /s6-init"]
networks:
  pihole_net:
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.20.0.0/24
    #       gateway: 172.20.0.1
    #       aux_addresses:
    #         pihole_ip: 172.20.0.2
