services:
  pihole:
    container_name: pihole
    build: .
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8314:80
      - 4314:443
    environment:
      TZ: America/Denver
      DNSMASQ_LISTENING: all
    volumes:
      - ./pihole_data_dir:/etc/pihole
      - ./dnsmasq_data_dir:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 192.168.86.241
    cap_add:
      - NET_ADMIN
    networks:
      - pihole_net
networks:
  pihole_net:
    driver: bridge