services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - 8026:8025   # web UI
      - 1025:1025   # SMTP
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATA_FILE: /data/mailpit.db

volumes:
  mailpit_data:
