services:
  mc_norm:
    container_name: mc_norm
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      MOTD: "Xanders survival, Chill Vibes Only"
      EULA: "TRUE"
      MEMORY: "1G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 28016
      restart: always
    volumes:
      - ./mc_norm:/data
